../src/Parameter_Definitions.sv
../src/A2Comp.sv
../src/add3.sv
../src/Adder.sv
../src/SIGN.sv
../src/BCD_7seg.sv
../src/binary_to_BCD_14B.sv 
../src/Counter.sv
../src/Register_Shifter.sv
../src/A2Comp_Multiplicands.sv
../src/Control_Unit.sv
../src/TOP_MOD.sv
../src/debouncer.sv
TOP_MOD_TB.sv